#!/usr/bin/env python3
"""Vendor the repo's evaluation stack into the clif-validate wheel (U9).

One implementation, two environments. The modules under the repository's `src/`
are the ONLY implementation of the export contract, disclosure controls,
attestation, tokenization, and inference. This script copies the closed import
set into `src/clif_validate/_vendor/`, mechanically rewriting the import prefix
(`from src.` / `import src.` → `clif_validate._vendor.`) and preserving the
`eval/` / `data/` / `model/` subpackage structure, so the wheel and the repo run
byte-identical logic.

Never edit a file under `_vendor/` by hand — edit the repo source and re-run:

    python clif-validate/scripts/sync_vendor.py          # sync
    python clif-validate/scripts/sync_vendor.py --check  # verify, exit 1 on drift

`vendor_manifest.json` records the SHA-256 of every SOURCE file at sync time.
`clif-validate/tests/test_bundle_compatibility.py` asserts both directions on
every test run — the manifest still matches `src/`, and each vendored file is
exactly the mechanical rewrite of its source — so drift on either side fails a
test rather than shipping silently.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

PKG_ROOT = Path(__file__).resolve().parents[1]     # clif-validate/
REPO_ROOT = PKG_ROOT.parent
VENDOR_ROOT = PKG_ROOT / "src" / "clif_validate" / "_vendor"
MANIFEST_PATH = VENDOR_ROOT / "vendor_manifest.json"

# The verified transitive import closure of the site-side entry points
# (clif_validate CLI + bundle + inference + synthetic self-test). Aggregator-side
# modules (method3, matrix, clif_forest_plot) are deliberately NOT vendored: the
# site package must not carry cross-site machinery. This list is wider than the
# plan's original four (schema/metrics/attestation/log_sanitizer) because closing
# the D1 inference seam pulls in tokenization, labeling, and the model heads.
VENDOR_FILES = (
    "src/eval/log_sanitizer.py",
    "src/eval/schema.py",
    "src/eval/metrics.py",
    "src/eval/attestation.py",
    "src/eval/clif_auto_labeler.py",
    "src/eval/clif_validate.py",
    "src/eval/trust.py",
    "src/eval/bundle.py",
    "src/eval/bundle_inference.py",
    "src/eval/synthetic_bundle.py",
    "src/data/splits.py",
    "src/data/cohort.py",
    "src/data/tokenize.py",
    "src/model/heads.py",
    "src/model/varlen_attention.py",
    "src/model/head_adapter.py",
)

# Import-statement contexts only. Docstring path mentions ("src/data/tokenize.py")
# contain slashes, and "python -m src.eval.method3" contains neither keyword-dot
# pattern, so neither is touched.
_IMPORT_RE = re.compile(r"\b(from|import)(\s+)src\.")

# Any residual top-level reference to the `src` package after rewrite: the covered
# `from src.` / `import src.` forms, plus the ones rewrite() does NOT touch —
# `from src import ...`, a bare `import src`, and string-literal module paths handed
# to importlib/__import__. Used by check() to fail closed on an uncovered import form.
_RESIDUAL_SRC_RE = re.compile(
    r"\b(?:from|import)\s+src\b|['\"]src(?:\.[A-Za-z0-9_]+)+['\"]"
)

_GENERATED_INIT = (
    '"""GENERATED by clif-validate/scripts/sync_vendor.py — do not edit."""\n'
)


def rewrite(text: str) -> str:
    return _IMPORT_RE.sub(lambda m: f"{m.group(1)}{m.group(2)}clif_validate._vendor.", text)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _vendored_path(rel: str, vendor_root: Path) -> Path:
    # src/eval/schema.py -> _vendor/eval/schema.py
    return vendor_root / Path(rel).relative_to("src")


def sync(repo_root: Path = REPO_ROOT, vendor_root: Path = VENDOR_ROOT) -> Path:
    vendor_root.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, str] = {}
    packages = set()
    for rel in VENDOR_FILES:
        source = (repo_root / rel).read_bytes()
        dest = _vendored_path(rel, vendor_root)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(rewrite(source.decode("utf-8")))
        manifest[rel] = _sha256(source)
        packages.add(dest.parent)
    (vendor_root / "__init__.py").write_text(_GENERATED_INIT)
    for pkg in packages:
        (pkg / "__init__.py").write_text(_GENERATED_INIT)
    manifest_path = vendor_root / "vendor_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest_path


def check(repo_root: Path = REPO_ROOT, vendor_root: Path = VENDOR_ROOT) -> list[str]:
    """Return a list of drift descriptions; empty means fully in sync."""
    problems: list[str] = []
    manifest_path = vendor_root / "vendor_manifest.json"
    if not manifest_path.exists():
        return [f"vendor manifest is missing: {manifest_path}"]
    manifest = json.loads(manifest_path.read_text())
    if set(manifest) != set(VENDOR_FILES):
        missing = sorted(set(VENDOR_FILES) - set(manifest))
        extra = sorted(set(manifest) - set(VENDOR_FILES))
        if missing:
            problems.append(f"manifest lacks entries for: {', '.join(missing)}")
        if extra:
            problems.append(f"manifest has stale entries for: {', '.join(extra)}")
    for rel in VENDOR_FILES:
        source_path = repo_root / rel
        vendored = _vendored_path(rel, vendor_root)
        if not source_path.exists():
            problems.append(f"repo source vanished: {rel}")
            continue
        if not vendored.exists():
            problems.append(f"vendored copy is missing: {vendored.name} (from {rel})")
            continue
        source = source_path.read_bytes()
        if rel in manifest and manifest[rel] != _sha256(source):
            problems.append(
                f"{rel} changed since the last sync (manifest hash is stale) — "
                "re-run sync_vendor.py"
            )
        vendored_text = vendored.read_text()
        if vendored_text != rewrite(source.decode("utf-8")):
            problems.append(
                f"{vendored.relative_to(vendor_root)} is not the mechanical rewrite "
                f"of {rel} — it was edited by hand or the sync is stale"
            )
        # `rewrite()` only rewrites `from src.` / `import src.`. An import form it does
        # NOT cover — `from src import x`, bare `import src`, importlib.import_module
        # ("src...") — would survive in BOTH source and vendored copy, so the equality
        # check above stays green while the installed wheel (no repo on sys.path) raises
        # ModuleNotFoundError (review finding). Flag any residual top-level `src`
        # reference in the vendored text directly.
        if _RESIDUAL_SRC_RE.search(vendored_text):
            problems.append(
                f"{vendored.relative_to(vendor_root)} still references the `src` "
                "package after rewrite — an import form sync_vendor's rewrite regex "
                "does not cover; extend rewrite() or change the source import"
            )
    # Vendored modules nobody vendored on purpose are drift too.
    expected = {_vendored_path(rel, vendor_root) for rel in VENDOR_FILES}
    for p in sorted(vendor_root.rglob("*.py")):
        if p.name == "__init__.py" or p in expected:
            continue
        problems.append(f"unexpected vendored module: {p.relative_to(vendor_root)}")
    # __init__.py files are executed on package import, so a hand-edited one is a live
    # code-injection surface — and the loop above skipped them before any content
    # check, so `schema.min_cell_size = lambda: 1` in _vendor/eval/__init__.py passed
    # every guard (review finding). Assert each is exactly what sync() writes.
    for p in sorted(vendor_root.rglob("__init__.py")):
        if p.read_text() != _GENERATED_INIT:
            problems.append(
                f"vendored {p.relative_to(vendor_root)} was edited by hand — an "
                "__init__.py runs on import and must contain only the generated stub"
            )
    return problems


def main() -> int:
    if "--check" in sys.argv[1:]:
        problems = check()
        for problem in problems:
            print(f"DRIFT: {problem}", file=sys.stderr)
        return 1 if problems else 0
    manifest_path = sync()
    print(f"vendored {len(VENDOR_FILES)} modules; manifest at {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
