table_name: ecmo_mcs
version: "2.1"

columns:
- name: hospitalization_id
  data_type: VARCHAR
  required: true
  is_category_column: false
  is_group_column: false
- name: recorded_dttm
  data_type: DATETIME
  required: true
  is_category_column: false
  is_group_column: false
- name: device_name
  data_type: VARCHAR
  required: false
  is_category_column: false
  is_group_column: false
- name: device_category
  data_type: VARCHAR
  required: true
  is_category_column: true
  is_group_column: false
  permissible_values:
  - Impella_2.5
  - Impella_CP
  - Impella_5.0
  - Impella_5.5
  - Impella_LD
  - Impella_RP
  - Impella_RP_Flex
  - iVAC
  - TandemHeart_LV
  - TandemHeart_RV
  - CentriMag_LV
  - CentriMag_RV
  - IABP
  - VA_ECMO
  - VV_ECMO
  - VAV_ECMO
  - LAVA_ECMO
  - HeartWare
  - HMII
  - HMIII
- name: mcs_group
  data_type: VARCHAR
  required: true
  is_category_column: false
  is_group_column: true
  permissible_values:
  - ECMO
  - IABP
  - RVAD
  - durable_LVAD
  - temporary_LVAD
- name: device_metric_name
  data_type: VARCHAR
  required: false
  is_category_column: false
  is_group_column: false
- name: device_rate
  data_type: FLOAT
  required: true
  is_category_column: false
  is_group_column: false
- name: sweep
  data_type: FLOAT
  required: true
  is_category_column: false
  is_group_column: false
- name: flow
  data_type: FLOAT
  required: true
  is_category_column: false
  is_group_column: false
- name: fdO2
  data_type: FLOAT
  required: true
  is_category_column: false
  is_group_column: false

required_columns:
  - hospitalization_id
  - recorded_dttm
  - device_category
  - mcs_group
  - device_rate
  - sweep
  - flow
  - fdO2

category_columns:
  - device_category

group_columns:
  - mcs_group
